sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t swiben/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swiben/react-test npm test
  
after_success:
  - docker build -t swiben/multi-client ./client
  - docker build -t swiben/multi-nginx ./nginx
  - docker build -t swiben/multi-server ./server
  - docker build -t swiben/multi-worker ./worker
# log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push swiben/multi-client
  - docker push swiben/multi-nginx
  - docker push swiben/multi-server
  - docker push swiben/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-470526744914'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY